// Trilhas novas: C#, JavaScript e Lua — mesmo padrão de profundidade das outras.
import type { Module, Section, Track } from "./modules";

const mk = (track: Track) =>
  (id: string, index: number, title: string, summary: string, duration: string, sections: Section[]): Module =>
    ({ id, track, index, title, summary, duration, sections });

const csh = mk("csharp");
const js = mk("javascript");
const lua = mk("lua");

export const EXTRA_MODULES: Module[] = [
  // ---------------- C# ----------------
  csh("cs-01", 1, "Como o C# roda: .NET, CLR e IL",
    "Antes de escrever código, entenda o caminho que seu programa percorre até virar execução de verdade.",
    "2h",
    [
      { heading: "O que é o .NET", body: "C# é a linguagem; .NET é a plataforma que executa. Você escreve .cs, o compilador (Roslyn) gera IL (Intermediate Language) dentro de um arquivo .dll, e o CLR (Common Language Runtime) traduz esse IL para código de máquina na hora de rodar, com um compilador JIT. Por isso o mesmo binário roda em Windows, Linux e macOS." },
      { heading: "Primeiro programa e top-level statements", body: "Desde o C# 10 você não precisa escrever a classe Program e o método Main na mão: o compilador cria isso pra você. Rode com `dotnet run`.", code: { lang: "csharp", source: `// Program.cs\nConsole.WriteLine("Olá, CrackDev!");\n\nvar nome = Console.ReadLine();\nConsole.WriteLine($"Bem-vindo, {nome}!");` } },
      { heading: "Comandos que você vai usar todo dia", body: "dotnet new console -o MeuApp (cria projeto), dotnet run (compila e roda), dotnet build (só compila), dotnet test (roda testes), dotnet add package X (instala biblioteca). O arquivo .csproj é a receita do projeto." },
      { heading: "Garbage collector em 1 minuto", body: "Você não libera memória na mão. O GC do .NET roda em gerações (0, 1 e 2): objetos novos morrem cedo e são coletados barato; os que sobrevivem sobem de geração. O que você precisa fazer é liberar recursos externos (arquivo, conexão) com `using`." },
      { heading: "Exercício", body: "Crie um console app que pergunta seu nome e sua idade, e imprime em quantos anos você faz 100. Rode com dotnet run e depois olhe a pasta bin/ para ver a .dll gerada." },
    ]),
  csh("cs-02", 2, "Tipos, valor vs referência e null safety",
    "A diferença entre struct e class explica 80% dos bugs de iniciante em C#.",
    "2h",
    [
      { heading: "Tipos de valor e de referência", body: "int, double, bool, char, DateTime e qualquer struct são TIPOS DE VALOR: ao atribuir, o conteúdo é copiado. class, string, array, List são TIPOS DE REFERÊNCIA: a variável guarda o endereço, então duas variáveis podem apontar para o mesmo objeto.", code: { lang: "csharp", source: `struct PontoV { public int X; }\nclass PontoR { public int X; }\n\nvar a = new PontoV { X = 1 };\nvar b = a;  b.X = 99;\nConsole.WriteLine(a.X); // 1  (cópia)\n\nvar c = new PontoR { X = 1 };\nvar d = c;  d.X = 99;\nConsole.WriteLine(c.X); // 99 (mesmo objeto)` } },
      { heading: "var, tipagem estática e implícita", body: "`var` NÃO é tipagem dinâmica: o compilador deduz o tipo e ele fica fixo. `dynamic` é que adia tudo pra execução — evite, você perde autocomplete e segurança." },
      { heading: "Nullable reference types", body: "Em projetos modernos (<Nullable>enable</Nullable>) o compilador avisa quando você pode receber null. `string?` aceita null; `string` promete que não. Use `?.` (safe navigation), `??` (valor padrão) e `??=`.", code: { lang: "csharp", source: `string? apelido = null;\nint tamanho = apelido?.Length ?? 0;  // 0, sem exceção\napelido ??= "sem apelido";` } },
      { heading: "Conversões", body: "int.Parse lança exceção se falhar; int.TryParse devolve bool e não quebra. Em entrada de usuário SEMPRE use TryParse." },
      { heading: "Armadilhas", body: "1) Comparar string com == funciona (compara conteúdo), diferente de Java. 2) Struct grande copiada em loop custa caro. 3) NullReferenceException quase sempre vem de ignorar um aviso do compilador." },
    ]),
  csh("cs-03", 3, "Controle de fluxo, coleções e pattern matching",
    "if, switch moderno, loops e as coleções que resolvem quase tudo.",
    "2h",
    [
      { heading: "Coleções essenciais", body: "List<T> = lista que cresce (índice O(1)). Dictionary<K,V> = chave→valor com busca O(1). HashSet<T> = conjunto sem repetição. Queue/Stack para fila e pilha. Array só quando o tamanho é fixo." },
      { heading: "Loops", body: "foreach para percorrer, for quando precisa do índice, while quando não sabe quantas voltas. Nunca modifique uma coleção enquanto faz foreach nela — dá InvalidOperationException." },
      { heading: "switch expression e pattern matching", body: "O switch moderno devolve valor e casa padrões, não só constantes.", code: { lang: "csharp", source: `string Faixa(int idade) => idade switch\n{\n    < 0    => "inválida",\n    < 13   => "criança",\n    < 18   => "adolescente",\n    < 60   => "adulto",\n    _      => "idoso"\n};\n\nif (obj is List<int> { Count: > 0 } lista)\n    Console.WriteLine(lista[0]);` } },
      { heading: "Exceções", body: "try/catch/finally. Capture o tipo específico (FormatException, IOException), nunca só `catch (Exception)` engolindo o erro. `using var f = File.OpenText(...)` fecha o arquivo sozinho no fim do escopo." },
      { heading: "Exercício", body: "Faça um menu de console (1 cadastrar, 2 listar, 3 remover, 0 sair) que guarda nomes em uma List<string> e usa switch expression para o texto do resultado." },
    ]),
  csh("cs-04", 4, "Orientação a objetos de verdade",
    "Classe, interface, herança, records e os princípios que evitam código impossível de manter.",
    "2h30",
    [
      { heading: "Classe, propriedade e construtor", body: "Propriedades (get/set) são métodos disfarçados: permitem validar e são a forma idiomática de expor dados. Prefira propriedades só-leitura definidas no construtor.", code: { lang: "csharp", source: `public class Aluno\n{\n    public string Nome { get; }\n    public int Idade { get; private set; }\n\n    public Aluno(string nome, int idade)\n    {\n        if (string.IsNullOrWhiteSpace(nome)) throw new ArgumentException("nome vazio");\n        Nome = nome; Idade = idade;\n    }\n\n    public void FazerAniversario() => Idade++;\n}` } },
      { heading: "Interface vs herança", body: "Interface diz O QUE a classe sabe fazer; herança diz O QUE ELA É. Regra prática: prefira interface + composição. Herde só quando existir uma relação real de 'é um'." },
      { heading: "record", body: "record cria um tipo imutável com igualdade por valor, ToString bonito e `with` para copiar mudando um campo. Perfeito para DTOs e modelos de dados.", code: { lang: "csharp", source: `public record Produto(string Nome, decimal Preco);\n\nvar p1 = new Produto("Curso", 40m);\nvar p2 = p1 with { Preco = 15m };\nConsole.WriteLine(p1 == new Produto("Curso", 40m)); // True` } },
      { heading: "SOLID na prática", body: "Uma classe = uma responsabilidade. Dependa de interface, não de implementação. Métodos pequenos. Se o construtor pede 8 coisas, a classe faz demais." },
      { heading: "Armadilhas", body: "Herdar só para reaproveitar código; usar `static` para tudo (vira estado global); expor campos públicos em vez de propriedades." },
    ]),
  csh("cs-05", 5, "LINQ: consultando dados sem for",
    "A ferramenta que mais economiza linhas em C# — e como não abusar dela.",
    "2h",
    [
      { heading: "A ideia", body: "LINQ te dá filtros, projeções e agregações sobre qualquer IEnumerable. É preguiçoso (lazy): a consulta só executa quando você percorre ou chama ToList()/Count()/First()." },
      { heading: "Operadores do dia a dia", body: "Where (filtra), Select (transforma), OrderBy/ThenBy (ordena), GroupBy (agrupa), Any/All (verifica), First/FirstOrDefault (pega um), Sum/Average/Max/Count (agrega), Take/Skip (paginação).", code: { lang: "csharp", source: `var alunos = new[]\n{\n    new { Nome = "Ana",  Nota = 9.0 },\n    new { Nome = "Beto", Nota = 5.5 },\n    new { Nome = "Caio", Nota = 7.2 },\n};\n\nvar aprovados = alunos\n    .Where(a => a.Nota >= 7)\n    .OrderByDescending(a => a.Nota)\n    .Select(a => $"{a.Nome} ({a.Nota:F1})")\n    .ToList();\n\nConsole.WriteLine(string.Join(", ", aprovados));\nConsole.WriteLine($"Média: {alunos.Average(a => a.Nota):F2}");` } },
      { heading: "Deferred execution", body: "Guardar a query em variável não executa nada. Se a fonte mudar depois, o resultado muda. Materialize com ToList() quando quiser congelar." },
      { heading: "Performance", body: "Cada operador cria um iterador. Em listas gigantes, encadear 8 operadores custa. Não chame Count() dentro de loop, e nunca faça consulta ao banco dentro de foreach (problema N+1)." },
      { heading: "Exercício", body: "Dada uma lista de pedidos (cliente, valor, data), use LINQ para: total por cliente, os 3 maiores pedidos e a média por mês." },
    ]),
  csh("cs-06", 6, "Async/await e programação assíncrona",
    "Como não travar seu programa esperando rede ou disco.",
    "2h15",
    [
      { heading: "Por que assíncrono", body: "Operações de I/O (HTTP, arquivo, banco) passam a maior parte do tempo esperando. `async/await` libera a thread durante a espera, em vez de deixá-la parada. Não é paralelismo: é não desperdiçar." },
      { heading: "A sintaxe", body: "Método marcado com `async` devolve Task ou Task<T>; `await` espera sem bloquear.", code: { lang: "csharp", source: `static readonly HttpClient http = new();\n\nasync Task<string> BuscarAsync(string url)\n{\n    using var resp = await http.GetAsync(url);\n    resp.EnsureSuccessStatusCode();\n    return await resp.Content.ReadAsStringAsync();\n}\n\n// Em paralelo:\nvar tarefas = urls.Select(BuscarAsync);\nstring[] todos = await Task.WhenAll(tarefas);` } },
      { heading: "Regras de ouro", body: "1) async o caminho inteiro — não misture .Result ou .Wait(), isso causa deadlock. 2) Nunca `async void`, exceto em handler de evento. 3) Use CancellationToken em tudo que pode demorar. 4) HttpClient é um só por aplicação (static), não um por chamada." },
      { heading: "Erros em código async", body: "A exceção fica guardada na Task e só estoura no await. try/catch em volta do await funciona normalmente; sem await, o erro some silenciosamente." },
      { heading: "Exercício", body: "Baixe 5 URLs em sequência medindo o tempo, depois com Task.WhenAll. Compare os números e explique a diferença." },
    ]),
  csh("cs-07", 7, "API REST com ASP.NET Core e Entity Framework",
    "Do zero a um endpoint funcionando com banco de dados.",
    "2h30",
    [
      { heading: "Minimal API", body: "Poucas linhas para uma API funcional. `dotnet new web` cria o projeto.", code: { lang: "csharp", source: `var builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddDbContext<AppDb>(o => o.UseSqlite("Data Source=app.db"));\nvar app = builder.Build();\n\napp.MapGet("/produtos", async (AppDb db) => await db.Produtos.ToListAsync());\n\napp.MapPost("/produtos", async (Produto p, AppDb db) =>\n{\n    db.Produtos.Add(p);\n    await db.SaveChangesAsync();\n    return Results.Created($"/produtos/{p.Id}", p);\n});\n\napp.Run();` } },
      { heading: "Injeção de dependência", body: "O ASP.NET tem DI embutido. AddScoped (um por requisição), AddSingleton (um por app), AddTransient (um por uso). Peça a dependência no construtor/parâmetro e o framework entrega." },
      { heading: "Entity Framework Core", body: "DbContext representa o banco, DbSet<T> representa a tabela. Migrations: dotnet ef migrations add Inicial && dotnet ef database update. Use AsNoTracking em leituras — mais rápido." },
      { heading: "Validação e status corretos", body: "Valide a entrada (DataAnnotations ou FluentValidation) e devolva os códigos certos: 200 ok, 201 criado, 400 entrada inválida, 404 não achou, 500 erro seu. Nunca devolva a exceção crua ao cliente." },
      { heading: "Exercício", body: "Construa uma API de tarefas com GET, POST, PUT e DELETE usando SQLite, com validação de título obrigatório." },
    ]),
  csh("cs-08", 8, "Testes, boas práticas e entrevista",
    "Fechando a trilha: qualidade de código e o que perguntam em processo seletivo.",
    "1h45",
    [
      { heading: "Testes com xUnit", body: "dotnet new xunit. [Fact] para caso único, [Theory] + [InlineData] para vários dados. Padrão Arrange-Act-Assert.", code: { lang: "csharp", source: `public class CalculadoraTests\n{\n    [Theory]\n    [InlineData(1, 2, 3)]\n    [InlineData(-1, 1, 0)]\n    public void Soma_RetornaTotal(int a, int b, int esperado)\n    {\n        var r = Calculadora.Soma(a, b);   // Act\n        Assert.Equal(esperado, r);        // Assert\n    }\n}` } },
      { heading: "Mocks", body: "Moq ou NSubstitute para substituir dependências externas. Teste a SUA regra, não o banco dos outros. Testes de integração à parte, com banco em memória ou container." },
      { heading: "Checklist de código profissional", body: "Nomes claros em inglês ou português, mas consistentes. Nada de método com 200 linhas. Sem número mágico. Log estruturado (ILogger). Configuração em appsettings, segredo em variável de ambiente." },
      { heading: "Perguntas de entrevista", body: "Diferença de struct e class; o que é boxing; IEnumerable vs IQueryable; como funciona o GC; por que async/await não cria thread; diferença de abstract class e interface; o que faz o `using`; value tuple vs record." },
      { heading: "Próximos passos", body: "Escolha um projeto real: API de finanças pessoais, bot de Discord ou joguinho em Unity (que usa C#). Terminar um projeto ensina mais que 10 tutoriais." },
    ]),

  // ---------------- JAVASCRIPT ----------------
  js("js-01", 1, "Como o JavaScript executa",
    "Engine, event loop e por que JS parece estranho no começo.",
    "2h",
    [
      { heading: "Onde o JS roda", body: "No navegador (engine V8 no Chrome, SpiderMonkey no Firefox) e no servidor com Node.js/Deno/Bun. A linguagem é a mesma; o que muda são as APIs disponíveis: no navegador existe `document`, no Node existe `fs`." },
      { heading: "Single thread + event loop", body: "JS executa em UMA thread. Tarefas demoradas (rede, timer) são entregues ao ambiente e voltam pela fila. O event loop pega a próxima tarefa quando a pilha esvazia — por isso um loop infinito trava a página inteira.", code: { lang: "javascript", source: `console.log("1");\nsetTimeout(() => console.log("3 — macrotask"), 0);\nPromise.resolve().then(() => console.log("2 — microtask"));\nconsole.log("1.5");\n// saída: 1, 1.5, 2, 3` } },
      { heading: "Onde escrever e testar", body: "Console do navegador (F12), arquivo .js rodado com `node arquivo.js`, ou um .html com <script type=\"module\" src=\"app.js\"></script>. Comece pelo console: retorno imediato ajuda a aprender." },
      { heading: "let, const e var", body: "Use `const` por padrão, `let` quando precisar reatribuir e NUNCA `var` (escopo de função + hoisting confuso). const não deixa reatribuir a variável, mas o conteúdo de um objeto/array continua alterável." },
      { heading: "Exercício", body: "No console, escreva um script que declara três variáveis, faz uma conta e imprime com template string. Depois adicione um setTimeout e preveja a ordem da saída antes de rodar." },
    ]),
  js("js-02", 2, "Tipos, coerção e as armadilhas famosas",
    "Por que 0.1 + 0.2 !== 0.3 e por que você deve usar ===.",
    "2h",
    [
      { heading: "Os tipos", body: "Primitivos: string, number, boolean, null, undefined, symbol, bigint. Todo o resto é object (inclusive array e function). typeof null === 'object' é um bug histórico da linguagem, mantido por compatibilidade." },
      { heading: "== vs ===", body: "`==` converte tipos antes de comparar e gera resultados absurdos. Use SEMPRE `===` e `!==`.", code: { lang: "javascript", source: `console.log(0 == "");      // true   😬\nconsole.log(0 === "");     // false  ✅\nconsole.log([] == false);  // true   😬\nconsole.log(null == undefined);  // true\nconsole.log(null === undefined); // false` } },
      { heading: "Valores falsy", body: "São falsy: false, 0, -0, 0n, \"\", null, undefined, NaN. Todo o resto é truthy — inclusive [] e {}. Por isso `if (lista)` não testa se a lista tem itens; use `if (lista.length)`." },
      { heading: "Números", body: "Todo number é float64. 0.1 + 0.2 === 0.30000000000000004. Para dinheiro, trabalhe em centavos (inteiros) ou use uma biblioteca decimal. Number.isNaN e Number.isInteger são os checadores confiáveis." },
      { heading: "Armadilhas", body: "'5' + 3 === '53' mas '5' - 3 === 2. NaN !== NaN. Sempre converta entrada de usuário com Number() ou parseInt(x, 10) e valide." },
    ]),
  js("js-03", 3, "Funções, escopo, closures e this",
    "O coração do JavaScript — domine isso e o resto encaixa.",
    "2h15",
    [
      { heading: "Funções são valores", body: "Você pode guardar função em variável, passar como argumento e retornar de outra função (isso é 'primeira classe'). É a base de map/filter, callbacks e eventos." },
      { heading: "Closure", body: "Uma função lembra do ambiente onde foi criada, mesmo depois que ele terminou. É como se cria estado privado.", code: { lang: "javascript", source: `function criarContador() {\n  let n = 0;                 // privado\n  return {\n    incrementar: () => ++n,\n    valor: () => n,\n  };\n}\n\nconst c = criarContador();\nc.incrementar(); c.incrementar();\nconsole.log(c.valor()); // 2\nconsole.log(c.n);       // undefined — protegido` } },
      { heading: "Arrow function e this", body: "Arrow (=>) NÃO tem `this` próprio: herda do escopo onde foi escrita. Função normal tem `this` definido por COMO é chamada. Em callbacks dentro de classe, use arrow para não perder o this." },
      { heading: "Parâmetros modernos", body: "Default (`function f(x = 1)`), rest (`...args` vira array) e spread (`f(...lista)`). Desestruturação em parâmetros deixa a assinatura legível: `function criar({ nome, idade = 0 })`." },
      { heading: "Exercício", body: "Implemente `once(fn)`: recebe uma função e devolve outra que só executa na primeira chamada, devolvendo sempre o primeiro resultado depois disso. Use closure." },
    ]),
  js("js-04", 4, "Arrays, objetos e imutabilidade",
    "As estruturas que você vai usar em 100% dos projetos.",
    "2h",
    [
      { heading: "Métodos de array que importam", body: "map (transforma), filter (seleciona), reduce (acumula), find/findIndex, some/every, sort, includes, flat, slice (copia) vs splice (modifica). Prefira os que devolvem novo array — código previsível.", code: { lang: "javascript", source: `const alunos = [\n  { nome: "Ana", nota: 9 },\n  { nome: "Beto", nota: 5 },\n  { nome: "Caio", nota: 7.5 },\n];\n\nconst aprovados = alunos.filter(a => a.nota >= 7).map(a => a.nome);\nconst media = alunos.reduce((s, a) => s + a.nota, 0) / alunos.length;\n\nconsole.log(aprovados); // ["Ana", "Caio"]\nconsole.log(media.toFixed(2)); // 7.17` } },
      { heading: "Objetos", body: "Object.keys/values/entries para percorrer, spread `{...obj}` para copiar (cópia rasa!), optional chaining `obj?.a?.b` e nullish `?? 'padrão'` para lidar com ausência." },
      { heading: "Cópia rasa vs profunda", body: "{...obj} copia só o primeiro nível: objetos internos continuam compartilhados. Para cópia profunda use structuredClone(obj)." },
      { heading: "Map e Set", body: "Map aceita qualquer chave e preserva ordem; Set elimina duplicados. Use quando a chave não for string ou quando precisar de add/has rápido." },
      { heading: "Exercício", body: "A partir de uma lista de vendas [{produto, valor, mes}], gere um objeto com o total por mês usando reduce e ordene os produtos por valor." },
    ]),
  js("js-05", 5, "Assíncrono: Promises, async/await e fetch",
    "Consumindo APIs sem cair no inferno de callbacks.",
    "2h15",
    [
      { heading: "Promise", body: "Um objeto que representa um valor que ainda vai chegar. Estados: pending → fulfilled (then) ou rejected (catch). Sempre trate o erro; promise rejeitada sem catch derruba processo no Node." },
      { heading: "async/await + fetch", body: "Açúcar sobre Promise que deixa o código com cara de síncrono.", code: { lang: "javascript", source: `async function buscarUsuario(id) {\n  try {\n    const resp = await fetch(\`https://api.exemplo.com/users/\${id}\`);\n    if (!resp.ok) throw new Error(\`HTTP \${resp.status}\`);\n    const dados = await resp.json();\n    return dados;\n  } catch (e) {\n    console.error("Falhou:", e.message);\n    return null;\n  }\n}\n\n// Em paralelo (muito mais rápido que em fila):\nconst [a, b] = await Promise.all([buscarUsuario(1), buscarUsuario(2)]);` } },
      { heading: "Atenção com fetch", body: "fetch NÃO rejeita em erro 404/500 — só em falha de rede. Sempre cheque `resp.ok`. Use AbortController para cancelar requisições que o usuário abandonou." },
      { heading: "Promise.all vs allSettled vs race", body: "all falha se qualquer uma falhar; allSettled devolve o resultado de todas; race devolve a primeira que terminar (útil para timeout)." },
      { heading: "Exercício", body: "Consuma https://api.github.com/users/SEU_USUARIO e mostre nome, repositórios públicos e avatar na página. Trate erro e mostre 'carregando…'." },
    ]),
  js("js-06", 6, "DOM e eventos: fazendo a página reagir",
    "Manipular HTML com JavaScript de forma limpa e acessível.",
    "2h",
    [
      { heading: "Selecionar e alterar", body: "document.querySelector / querySelectorAll. Altere com textContent (seguro) e classList.add/remove/toggle. Evite innerHTML com dados do usuário — é porta de entrada para XSS.", code: { lang: "javascript", source: `const btn = document.querySelector("#salvar");\nconst lista = document.querySelector("#itens");\n\nbtn.addEventListener("click", (e) => {\n  e.preventDefault();\n  const li = document.createElement("li");\n  li.textContent = document.querySelector("#campo").value;\n  lista.append(li);\n});` } },
      { heading: "Eventos e delegação", body: "Em vez de um listener por item, ponha um no pai e use e.target.closest('.item'). Funciona para itens criados depois e gasta menos memória." },
      { heading: "Formulários", body: "Escute 'submit' no form (não 'click' no botão), chame e.preventDefault(), leia com new FormData(form). Mantenha a validação nativa do HTML como primeira camada." },
      { heading: "Performance e acessibilidade", body: "Agrupe alterações (DocumentFragment) para evitar reflow. Use elementos semânticos e sempre deixe o teclado funcionar: <button> em vez de <div onclick>." },
      { heading: "Exercício", body: "Faça uma lista de tarefas: adicionar, marcar como concluída (classList.toggle), remover (delegação) e salvar em localStorage." },
    ]),
  js("js-07", 7, "Módulos, ferramentas e Node.js",
    "Saindo do arquivo único para um projeto de verdade.",
    "2h",
    [
      { heading: "ES Modules", body: "export/import é o padrão. No navegador precisa de <script type=\"module\">; no Node, use extensão .mjs ou \"type\": \"module\" no package.json.", code: { lang: "javascript", source: `// math.js\nexport function soma(a, b) { return a + b; }\nexport default function media(lista) {\n  return lista.reduce((s, n) => s + n, 0) / lista.length;\n}\n\n// app.js\nimport media, { soma } from "./math.js";\nconsole.log(soma(2, 3), media([1, 2, 3]));` } },
      { heading: "npm e package.json", body: "npm init -y cria o projeto; npm i pacote instala; scripts guardam comandos (npm run dev). package-lock.json trava versões — commite ele. node_modules nunca vai pro git." },
      { heading: "Node básico", body: "fs/promises para arquivos, path para caminhos, process.env para configuração, http ou Express para servidor. Nada de segredo escrito no código: use variável de ambiente." },
      { heading: "Qualidade", body: "ESLint pega erro antes de rodar; Prettier formata; Vitest/Jest testam; TypeScript (próximo passo natural) adiciona tipos e elimina uma classe inteira de bugs." },
      { heading: "Exercício", body: "Crie um projeto com npm, separe funções em módulos, adicione um script `npm start` e leia um arquivo JSON com fs/promises." },
    ]),
  js("js-08", 8, "Projeto final, boas práticas e entrevista",
    "Consolidando tudo e se preparando para o mercado.",
    "1h45",
    [
      { heading: "Projeto sugerido", body: "App de clima: campo de cidade → fetch em uma API pública → renderiza cards com o DOM → salva as últimas buscas no localStorage → trata erro e estado de carregando. Usa TUDO que você viu na trilha." },
      { heading: "Boas práticas", body: "Funções pequenas com um objetivo. Nomes descritivos (nada de `x`, `data2`). const por padrão. Sem lógica dentro do HTML. Trate erro sempre. Separe: dados, lógica e apresentação." },
      { heading: "Segurança no front", body: "Nunca confie no cliente: validação real acontece no servidor. Não coloque chave secreta no JS do navegador. Escape conteúdo do usuário (textContent) para evitar XSS." },
      { heading: "Perguntas de entrevista", body: "Explique event loop, microtask vs macrotask; closure com exemplo; diferença de var/let/const; == vs ===; o que é hoisting; como o `this` é definido; Promise.all vs allSettled; cópia rasa vs profunda; debounce vs throttle." },
      { heading: "Depois daqui", body: "TypeScript e depois um framework (React é o caminho mais direto para emprego). Mas só avance quando conseguir escrever o app de clima sem consultar tutorial." },
    ]),

  // ---------------- LUA ----------------
  lua("lua-01", 1, "Lua: a linguagem pequena que roda em todo lugar",
    "Por que Lua é usada em jogos (Roblox, World of Warcraft), Nginx, Redis e dispositivos embarcados.",
    "1h30",
    [
      { heading: "O que é Lua", body: "Uma linguagem brasileira (PUC-Rio), minúscula (o interpretador cabe em ~250 KB), rápida e feita para ser EMBARCADA dentro de outros programas. Por isso ela é a linguagem de script de jogos, de plugins do Neovim, do OpenResty e de muitos dispositivos IoT." },
      { heading: "Rodando seu primeiro script", body: "Instale o `lua` (ou use o LuaJIT). Rode `lua arquivo.lua` ou abra o REPL só digitando `lua`.", code: { lang: "lua", source: `print("Olá, CrackDev!")\n\nlocal nome = "Davi"\nlocal idade = 20\nprint(("%s tem %d anos"):format(nome, idade))\n-- comentário de uma linha\n--[[ comentário\n     de várias linhas ]]` } },
      { heading: "Diferenças que assustam no começo", body: "1) Índices começam em 1, não 0. 2) Blocos terminam com `end`, não chaves. 3) Diferente é `~=`, não `!=`. 4) Concatenação é `..`, não `+`. 5) Só `nil` e `false` são falsos — 0 e \"\" são VERDADEIROS." },
      { heading: "local é obrigatório na prática", body: "Sem `local`, a variável vira global e polui todo o programa (fonte clássica de bug em mods de jogo). Escreva `local` sempre, exceto quando quiser global de propósito." },
      { heading: "Exercício", body: "Escreva um script que recebe uma temperatura em Celsius numa variável e imprime em Fahrenheit e Kelvin, usando string.format com 1 casa decimal." },
    ]),
  lua("lua-02", 2, "Tipos, variáveis e controle de fluxo",
    "Os oito tipos da linguagem e como decidir caminhos.",
    "1h45",
    [
      { heading: "Os tipos", body: "nil, boolean, number, string, function, table, userdata e thread. É só isso — a simplicidade é proposital. type(x) devolve o nome do tipo." },
      { heading: "Números e strings", body: "Desde o Lua 5.3 existe inteiro e float separados (3 vs 3.0). Strings são imutáveis e têm métodos via `:` — s:upper(), s:len(), s:sub(1,3), s:find('a'), s:gsub('a','b')." },
      { heading: "if, while, for e repeat", body: "for numérico tem início, fim e passo opcional (o fim é INCLUSIVO).", code: { lang: "lua", source: `local nota = 7.5\n\nif nota >= 9 then\n  print("excelente")\nelseif nota >= 7 then\n  print("aprovado")\nelse\n  print("reprovado")\nend\n\nfor i = 1, 5 do print(i) end        -- 1 2 3 4 5\nfor i = 10, 1, -2 do print(i) end   -- 10 8 6 4 2\n\nlocal n = 0\nrepeat n = n + 1 until n >= 3       -- roda pelo menos uma vez` } },
      { heading: "Operadores lógicos como atalho", body: "`and`/`or` devolvem VALOR, não booleano. Idioma clássico: `local x = valor or padrao` (default) e `local y = cond and a or b` (ternário improvisado — cuidado se `a` for false/nil)." },
      { heading: "Exercício", body: "Faça um jogo de adivinhação: sorteie um número com math.random(1,100), leia palpites com io.read('n') e diga 'maior'/'menor' até acertar, contando as tentativas." },
    ]),
  lua("lua-03", 3, "Tables: a única estrutura de dados",
    "Array, dicionário, objeto e módulo — tudo é table em Lua.",
    "2h",
    [
      { heading: "Table como array e como dicionário", body: "A mesma table guarda parte sequencial (1..n) e parte associativa (chaves quaisquer).", code: { lang: "lua", source: `local frutas = { "maçã", "uva", "pera" }   -- índices 1,2,3\nprint(frutas[1], #frutas)                  -- maçã   3\n\nlocal aluno = { nome = "Ana", nota = 9.5 }\nprint(aluno.nome, aluno["nota"])\n\ntable.insert(frutas, "kiwi")\ntable.remove(frutas, 1)\ntable.sort(frutas)\nprint(table.concat(frutas, ", "))` } },
      { heading: "Percorrendo", body: "`ipairs` percorre só a parte sequencial em ordem e PARA no primeiro nil. `pairs` percorre todas as chaves, em ordem indefinida. Escolher errado é bug silencioso." },
      { heading: "O buraco no array", body: "Se você faz t[1], t[2], t[4], o `#t` fica indefinido (pode ser 2 ou 4). Nunca deixe furos: use table.remove para tirar item, não `t[i] = nil`." },
      { heading: "Tables aninhadas", body: "Table dentro de table modela qualquer coisa: matriz, JSON, árvore, estado de jogo. Como table é referência, passar para função não copia — alterou lá, alterou aqui." },
      { heading: "Exercício", body: "Monte um inventário de jogo: table de itens {nome, quantidade, preco}, funções para adicionar, remover, calcular o valor total e listar ordenado por preço." },
    ]),
  lua("lua-04", 4, "Funções, escopo e closures",
    "Funções em Lua são valores de primeira classe — isso abre muita coisa.",
    "1h45",
    [
      { heading: "Definindo funções", body: "Funções podem receber e devolver MÚLTIPLOS valores, algo raro em outras linguagens.", code: { lang: "lua", source: `local function divmod(a, b)\n  return a // b, a % b        -- dois retornos\nend\n\nlocal q, r = divmod(17, 5)\nprint(q, r)  -- 3   2\n\nlocal function soma(...)      -- varargs\n  local t = 0\n  for _, n in ipairs({...}) do t = t + n end\n  return t\nend\nprint(soma(1, 2, 3, 4))  -- 10` } },
      { heading: "Closures", body: "Funções capturam variáveis locais do escopo onde nasceram (upvalues). É assim que se cria contador, cache e estado privado sem classe." },
      { heading: "Funções como argumento", body: "Passar função é o padrão para callbacks de eventos em jogos e para ordenação customizada: table.sort(t, function(a,b) return a.preco < b.preco end)." },
      { heading: "Erros: pcall", body: "Lua não tem try/catch; usa `pcall(f, args)` que devolve ok, resultado_ou_erro. `error('mensagem')` lança. Em scripts embarcados, SEMPRE proteja o que pode falhar com pcall para não derrubar o host." },
      { heading: "Exercício", body: "Crie `memoize(fn)` que guarda resultados já calculados numa table e devolve instantâneo na segunda chamada. Teste com fibonacci recursivo." },
    ]),
  lua("lua-05", 5, "Metatables, OOP e herança",
    "O mecanismo mais poderoso de Lua, explicado devagar.",
    "2h15",
    [
      { heading: "O que é uma metatable", body: "Uma table que define COMO outra table se comporta em situações especiais: o que acontece ao somar duas tables (__add), ao imprimir (__tostring), ao acessar chave que não existe (__index). setmetatable(t, mt) liga as duas." },
      { heading: "__index é a herança", body: "Quando a chave não existe na table, Lua olha no __index da metatable. É exatamente assim que se faz orientação a objetos.", code: { lang: "lua", source: `local Animal = {}\nAnimal.__index = Animal\n\nfunction Animal.new(nome, som)\n  return setmetatable({ nome = nome, som = som }, Animal)\nend\n\nfunction Animal:falar()               -- ':' cria o parâmetro self\n  print(self.nome .. " faz " .. self.som)\nend\n\nlocal Cachorro = setmetatable({}, { __index = Animal })\nCachorro.__index = Cachorro\n\nfunction Cachorro.new(nome)\n  local o = Animal.new(nome, "au au")\n  return setmetatable(o, Cachorro)\nend\n\nfunction Cachorro:buscar() print(self.nome .. " buscou a bolinha") end\n\nlocal rex = Cachorro.new("Rex")\nrex:falar()   -- herdado de Animal\nrex:buscar()` } },
      { heading: "Ponto vs dois-pontos", body: "obj:metodo(x) é açúcar para obj.metodo(obj, x). Use `:` ao definir e chamar métodos; use `.` para funções que não precisam de self. Misturar é o erro nº 1 de quem começa." },
      { heading: "Outros metamétodos úteis", body: "__tostring (print bonito), __eq/__lt (comparação), __add/__sub/__mul (operadores), __call (table vira função), __newindex (intercepta escrita, permite table só-leitura)." },
      { heading: "Exercício", body: "Crie uma classe Vetor2 com __add, __sub, __eq e __tostring, e uma subclasse Vetor3 herdando os métodos." },
    ]),
  lua("lua-06", 6, "Módulos, biblioteca padrão e arquivos",
    "Organizando o código e usando o que já vem pronto.",
    "1h45",
    [
      { heading: "Criando um módulo", body: "Um módulo é um arquivo que devolve uma table. require carrega uma única vez e faz cache.", code: { lang: "lua", source: `-- mathx.lua\nlocal M = {}\n\nfunction M.media(t)\n  local s = 0\n  for _, v in ipairs(t) do s = s + v end\n  return s / #t\nend\n\nreturn M\n\n-- main.lua\nlocal mathx = require("mathx")\nprint(mathx.media({1, 2, 3}))` } },
      { heading: "Biblioteca padrão", body: "string (format, gsub, find, sub, rep), table (insert, remove, sort, concat), math (random, floor, ceil, abs, max, huge), os (time, date, clock, getenv), io (open, read, write, lines)." },
      { heading: "Arquivos", body: "local f = io.open('dados.txt','r'); leia com f:read('a') ou for linha in f:lines(); feche com f:close(). Sempre cheque se f é nil (arquivo pode não existir)." },
      { heading: "Padrões Lua (não é regex)", body: "Lua tem um sistema próprio, mais simples: %d dígito, %a letra, %s espaço, %w alfanumérico, + 1 ou mais, - preguiçoso, * zero ou mais. Ex: s:gsub('%s+', ' ') normaliza espaços." },
      { heading: "Exercício", body: "Leia um arquivo .txt de nomes, remova linhas em branco, ordene alfabeticamente e grave o resultado em outro arquivo." },
    ]),
  lua("lua-07", 7, "Lua na prática: jogos e scripting",
    "Onde Lua realmente aparece no mercado e como se encaixar nesses ambientes.",
    "2h",
    [
      { heading: "Game loop", body: "Em engines (LÖVE, Roblox, Defold, Corona) você não escreve o loop: implementa callbacks que a engine chama. Padrão: load (carregar), update(dt) (lógica, use dt para ficar independente de FPS) e draw (desenhar).", code: { lang: "lua", source: `-- LÖVE (love2d): main.lua\nlocal x, y, vel = 100, 100, 200\n\nfunction love.load()\n  love.window.setTitle("Meu jogo")\nend\n\nfunction love.update(dt)\n  if love.keyboard.isDown("right") then x = x + vel * dt end\n  if love.keyboard.isDown("left")  then x = x - vel * dt end\nend\n\nfunction love.draw()\n  love.graphics.circle("fill", x, y, 20)\nend` } },
      { heading: "Roblox (Luau)", body: "Roblox usa Luau, um dialeto de Lua com tipos opcionais. Scripts ficam em objetos, comunicação entre cliente e servidor via RemoteEvent. Regra de ouro: NUNCA confie no cliente — valide tudo no servidor." },
      { heading: "Embarcando Lua em outro programa", body: "Lua foi feita para ser chamada de C/C++: o programa host expõe funções e o usuário escreve scripts. É por isso que mods, plugins e configuração dinâmica usam Lua." },
      { heading: "Performance", body: "Evite criar tables dentro do update (pressiona o GC): reaproveite. Guarde funções muito usadas em locals (`local sin = math.sin`) — acesso local é mais rápido que global. LuaJIT acelera muito código numérico." },
      { heading: "Exercício", body: "Implemente a lógica de um Pong (sem gráficos): posições, velocidades, colisão com as bordas e placar, atualizadas por uma função update(dt) chamada num loop." },
    ]),
  lua("lua-08", 8, "Depuração, boas práticas e projeto final",
    "Fechando a trilha com código limpo e um projeto que você mostra pra alguém.",
    "1h30",
    [
      { heading: "Depurando", body: "print é seu amigo, mas use com contexto: print('DEBUG x =', x). Percorra tables com uma função dump recursiva. pcall isola falhas. Em editores, o plugin Lua Language Server dá autocomplete e detecta variável global acidental." },
      { heading: "Erros comuns", body: "1) Esquecer `local` e criar global. 2) Confundir `.` com `:` em método. 3) Usar índice 0. 4) Comparar com != em vez de ~=. 5) Usar # em table com furos. 6) Achar que 0 é falso." },
      { heading: "Estilo", body: "snake_case para variáveis e funções, PascalCase para 'classes'. Um módulo por arquivo, retornando uma table. Funções curtas. Comente o PORQUÊ, não o o quê." },
      { heading: "Projeto final", body: "Um RPG de texto: tables para jogador, inimigos e itens; metatables para as classes de personagem; módulos separados (combate, inventário, save); salvar o progresso em arquivo; menu no terminal com io.read." },
      { heading: "Perguntas de entrevista", body: "O que é metatable e __index; diferença de pairs e ipairs; por que só nil e false são falsos; como Lua faz OOP sem class; o que é closure/upvalue; como tratar erro sem try/catch; por que Lua é escolhida para embarcar." },
    ]),
];
