/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCursoIndexRouteImport } from './routes/_authenticated/curso.index'
import { Route as AuthenticatedCursoModuleIdRouteImport } from './routes/_authenticated/curso.$moduleId'
import { Route as AuthenticatedCertificadoTrackRouteImport } from './routes/_authenticated/certificado.$track'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursoIndexRoute = AuthenticatedCursoIndexRouteImport.update({
  id: '/curso/',
  path: '/curso/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursoModuleIdRoute =
  AuthenticatedCursoModuleIdRouteImport.update({
    id: '/curso/$moduleId',
    path: '/curso/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificadoTrackRoute =
  AuthenticatedCertificadoTrackRouteImport.update({
    id: '/certificado/$track',
    path: '/certificado/$track',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/ia': typeof AuthenticatedIaRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/certificado/$track': typeof AuthenticatedCertificadoTrackRoute
  '/curso/$moduleId': typeof AuthenticatedCursoModuleIdRoute
  '/curso/': typeof AuthenticatedCursoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/ia': typeof AuthenticatedIaRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/certificado/$track': typeof AuthenticatedCertificadoTrackRoute
  '/curso/$moduleId': typeof AuthenticatedCursoModuleIdRoute
  '/curso': typeof AuthenticatedCursoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/certificado/$track': typeof AuthenticatedCertificadoTrackRoute
  '/_authenticated/curso/$moduleId': typeof AuthenticatedCursoModuleIdRoute
  '/_authenticated/curso/': typeof AuthenticatedCursoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comprar'
    | '/reset-password'
    | '/admin'
    | '/busca'
    | '/ia'
    | '/progresso'
    | '/certificado/$track'
    | '/curso/$moduleId'
    | '/curso/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comprar'
    | '/reset-password'
    | '/admin'
    | '/busca'
    | '/ia'
    | '/progresso'
    | '/certificado/$track'
    | '/curso/$moduleId'
    | '/curso'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/comprar'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/busca'
    | '/_authenticated/ia'
    | '/_authenticated/progresso'
    | '/_authenticated/certificado/$track'
    | '/_authenticated/curso/$moduleId'
    | '/_authenticated/curso/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComprarRoute: typeof ComprarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/': {
      id: '/_authenticated/curso/'
      path: '/curso'
      fullPath: '/curso/'
      preLoaderRoute: typeof AuthenticatedCursoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/$moduleId': {
      id: '/_authenticated/curso/$moduleId'
      path: '/curso/$moduleId'
      fullPath: '/curso/$moduleId'
      preLoaderRoute: typeof AuthenticatedCursoModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificado/$track': {
      id: '/_authenticated/certificado/$track'
      path: '/certificado/$track'
      fullPath: '/certificado/$track'
      preLoaderRoute: typeof AuthenticatedCertificadoTrackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedCertificadoTrackRoute: typeof AuthenticatedCertificadoTrackRoute
  AuthenticatedCursoModuleIdRoute: typeof AuthenticatedCursoModuleIdRoute
  AuthenticatedCursoIndexRoute: typeof AuthenticatedCursoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedCertificadoTrackRoute: AuthenticatedCertificadoTrackRoute,
  AuthenticatedCursoModuleIdRoute: AuthenticatedCursoModuleIdRoute,
  AuthenticatedCursoIndexRoute: AuthenticatedCursoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComprarRoute: ComprarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
