/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCursoIndexRouteImport } from './routes/_authenticated/curso.index'
import { Route as AuthenticatedCursoModuleIdRouteImport } from './routes/_authenticated/curso.$moduleId'

const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursoIndexRoute = AuthenticatedCursoIndexRouteImport.update({
  id: '/curso/',
  path: '/curso/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursoModuleIdRoute =
  AuthenticatedCursoModuleIdRouteImport.update({
    id: '/curso/$moduleId',
    path: '/curso/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/curso/$moduleId': typeof AuthenticatedCursoModuleIdRoute
  '/curso/': typeof AuthenticatedCursoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/curso/$moduleId': typeof AuthenticatedCursoModuleIdRoute
  '/curso': typeof AuthenticatedCursoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/curso/$moduleId': typeof AuthenticatedCursoModuleIdRoute
  '/_authenticated/curso/': typeof AuthenticatedCursoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comprar'
    | '/admin'
    | '/curso/$moduleId'
    | '/curso/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/comprar' | '/admin' | '/curso/$moduleId' | '/curso'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/comprar'
    | '/_authenticated/admin'
    | '/_authenticated/curso/$moduleId'
    | '/_authenticated/curso/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComprarRoute: typeof ComprarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/': {
      id: '/_authenticated/curso/'
      path: '/curso'
      fullPath: '/curso/'
      preLoaderRoute: typeof AuthenticatedCursoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/$moduleId': {
      id: '/_authenticated/curso/$moduleId'
      path: '/curso/$moduleId'
      fullPath: '/curso/$moduleId'
      preLoaderRoute: typeof AuthenticatedCursoModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCursoModuleIdRoute: typeof AuthenticatedCursoModuleIdRoute
  AuthenticatedCursoIndexRoute: typeof AuthenticatedCursoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCursoModuleIdRoute: AuthenticatedCursoModuleIdRoute,
  AuthenticatedCursoIndexRoute: AuthenticatedCursoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComprarRoute: ComprarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
